### PR TITLE
Upgrade to latest Layer0, and Add GitHub Workflow

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by tristanlee85** [comment]
You should use this workflow for 1-click deploy: https://github.com/layer0-docs/layer0-nextjs-example/blob/master/.github/workflows/layer0.yml . What you currently have will not work because environments aren't setup for the user.

**Comment by rishi-raj-jain** [comment]
It should work I think given that it deploys to default for the main branch (which is the branch created with a new deployment). Let me fetch you an example.

**Comment by rishi-raj-jain** [comment]
An example: https://github.com/rishi-raj-jain/test-layer0-gatsby-example
Deployed with App.layer0.deploy: https://github.com/rishi-raj-jain/test-layer0-gatsby-example/runs/4357065166?check_suite_focus=true

**Comment by rishi-raj-jain** [comment]
> You should use this workflow for 1-click deploy: https://github.com/layer0-docs/layer0-nextjs-example/blob/master/.github/workflows/layer0.yml . What you currently have will not work because environments aren't setup for the user.

Thanks for that tip, updated ✅

**Review by jeffpatzer — APPROVED** [review]

**Pull request merged**
